trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: playwright-secrets

steps:
  - script: |
      echo "LOGIN_USER: $LOGIN_USER"
      echo "LOGIN_PASSWORD definido? ${LOGIN_PASSWORD:+sim}"
    displayName: 'Verificar variáveis de ambiente'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Instalar Node.js'

  - script: npm ci
    displayName: 'Instalar dependências do projeto'

steps:
  - script: npx playwright install --with-deps
    displayName: 'Instalar Playwright'

  - script: |
      echo "Executando testes com login $LOGIN_USER"
      npx playwright test
    displayName: 'Executar testes Playwright'