trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Instalar Node.js'

  - script: |
      npm ci
      npx playwright install
    displayName: 'Instalar dependências'

  - script: npx playwright test
    displayName: 'Executar testes Playwright'

